# -*- mode: ruby -*-
# vi: set ft=ruby :

# The OpenTRV project licenses this file to you
# under the Apache Licence, Version 2.0 (the "Licence");
# you may not use this file except in compliance
# with the Licence. You may obtain a copy of the Licence at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the Licence is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied. See the Licence for the
# specific language governing permissions and limitations
# under the Licence.
#
# Author(s) / Copyright (s): Bruno Girin 2016

Vagrant.configure(2) do |config|
    # Set the box name to the OpenStack one, to be overriden in VirtualBox
    # config to work around OpenStack provider weirdness
    config.vm.box = "trusty"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    # Set Timezone for VM
    config.timezone.value = "UTC" if Vagrant.has_plugin?("vagrant-timezone")

    # Bootstrap the machine
    config.vm.provision "shell", :path => "vm/bootstrap.sh"

    # Install necessary software packages
    config.vm.provision "shell", :path => "vm/install.sh"

    config.vm.provider "virtualbox" do |vb, override|
        # Give VM 1/3 system memory & access to all cpu cores on the host
        host = RbConfig::CONFIG['host_os']
        if host =~ /darwin/
            cpus = `sysctl -n hw.ncpu`.to_i
            # sysctl returns Bytes and we need to convert to MB
            mem_host = `sysctl -n hw.memsize`.to_i / 1024 / 1024
            case
            when mem_host > 8732
                mem_factor = 2
            else
                mem_factor = 3
            end
            mem = mem_host / mem_factor
        elsif host =~ /linux/
            cpus = `nproc`.to_i
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 3
        else # sorry Windows folks, I can't help you
            cpus = 2
            mem = 1024
        end
        vb.customize ["modifyvm", :id, "--memory", mem]
        vb.customize ["modifyvm", :id, "--cpus",cpus]
    end
end
