# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    # Set the box name to the OpenStack one, to be overriden in VirtualBox
    # config to work around OpenStack provider weirdness
    config.vm.box = "trusty"
    config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

    # Set Timezone for VM
    config.timezone.value = "UTC" if Vagrant.has_plugin?("vagrant-timezone")

    # Bootstrap the machine by performing a minimal puppet install
    #config.vm.provision "shell", :path => "vagrant/dev/bootstrap.sh"

    # Workaround to set the hostname without vagrant overriding /etc/hosts
    #config.vm.provision "shell", :inline => "hostname #{vm_hostname}"

    config.vm.provider "virtualbox" do |vb, override|
        # Give VM 1/3 system memory & access to all cpu cores on the host
        host = RbConfig::CONFIG['host_os']
        if host =~ /darwin/
            cpus = `sysctl -n hw.ncpu`.to_i
            # sysctl returns Bytes and we need to convert to MB
            mem_host = `sysctl -n hw.memsize`.to_i / 1024 / 1024
            case
            when mem_host > 8732
                mem_factor = 2
            else
                mem_factor = 3
            end
            mem = mem_host / mem_factor
        elsif host =~ /linux/
            cpus = `nproc`.to_i
            # meminfo shows KB and we need to convert to MB
            mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 / 3
        else # sorry Windows folks, I can't help you
            cpus = 2
            mem = 1024
        end
        vb.customize ["modifyvm", :id, "--memory", mem]
        vb.customize ["modifyvm", :id, "--cpus",cpus]
    end
end
